### ISSUE TITLE
Address validation - shippo.address.create()

### ISSUE THREAD

**Issue by gbruins** [goshippo/shippo-node-client#41]
I sent known incorrect address data to test address validation:

street1=166 sylvan ave   (number 166 does not exist)
city=san mateoo  (too many 'o's.. should be 'san mateo')
state=CA
zip=94401  (correct zip is 94403)
country=US

The API response returned  "is_valid": true, as well as the *correct* zip and city name:

```javascript
{
  "data": {
    "object_created": "2017-07-27T03:56:02.918Z",
    "object_updated": "2017-07-27T03:56:03.456Z",
    "object_id": "97586d355f564c3a90519fc0c2fe7ce5",
    "is_complete": true,
    "validation_results": {
      "is_valid": true,    <======================
      "messages": [
        
      ]
    },
    "object_owner": "xxxxxxxxxx",
    "name": "",
    "company": "",
    "street_no": "",
    "street1": "166 SYLVAN AVE",
    "street2": "",
    "street3": "",
    "city": "SAN MATEO",   <======================
    "state": "CA",
    "zip": "94403",   <======================
    "country": "US",
    "longitude": null,
    "latitude": null,
    "phone": "",
    "email": "",
    "is_residential": null,
    "metadata": "",
    "test": true
  }
}
```

I was expecting "is_valid": false since I submitted incorrect data.  Is this by design?

**Comment by mootrichard** [comment]
Our address validation service will actually return a corrected address if it is close enough to a valid address. That is why you're seeing the city name corrected and the zip code corrected. As for the street number, I couldn't be sure why that wasn't corrected. If you had provided everything on the `street1` that could possibly explain why.

**Comment by gbruins** [comment]
Got it thanks @mootrichard.   Perhaps the docs can be updated to describe this nuance, because it seems in this case, the host application should be updating the user input with the corrected address info, to avoid an undeliverable package.  Does that sound right?

https://goshippo.com/docs/address-validation

**Comment by mootrichard** [comment]
I think that's an excellent point and will be sure to include information in the docs to highlight that a corrected address would be returned. 

I have actually been recently working on updating the docs around address validation since we have some developments going out on that endpoint soon, so there are a few things that need to be updated around that anyways.

The address validation that you receive back would at _least_ give you a corrected address that you can give back to a user in order to have them confirm if the address that you received is correct. This would ensure that you have a verified deliverable address, and that your user gets their delivery. If the returned address is off from their actual address, you can give an opportunity to provide a corrected address to try again.

If we simply rejected the address, the user would simply have to keep trying until they got something right (like maybe the address should be UNIT instead of APT), but a corrected address lets you diff their input against the correction and provide an alternative suggestion.

**Comment by gbruins** [comment]
Excellent suggestion @mootrichard.
