### ISSUE TITLE
Create Shipment returns empty Rates with async: true

### ISSUE THREAD

**Issue by KyrosDigital** [goshippo/shippo-node-client#42]
Hi there, 

When I make the request to create a shipment in order to retrieve the rates, the rates Array returns empty, but only when using "async": true. 

When "async": false is set, the rates Array seems to work fine.  

I've searched high, low in the docs, and have tried test key, live key, enabled a payment method, you name it, the async setting on false seems to be the culprit. 

What is causing this? It's would be great to keep the integration async all the way. 

Thanks!

**Comment by mootrichard** [comment]
This is because when you do your request asynchronously, we won't return the rates right away. You'll notice that in the response you're returned a status of "QUEUED". This indicates that we haven't retrieve rates for it yet, and you would need to query it again at a later time to see if the rates have been retrieved yet.

You can find a little more info on this at [https://goshippo.com/docs/async](https://goshippo.com/docs/async)

**Comment by KyrosDigital** [comment]
This now makes perfect sense, thanks for your help!
