### ISSUE TITLE
How to use OAuth with the SDK?

### ISSUE THREAD

**Issue by Akumzy** [goshippo/shippo-node-client#85]
How can I use the OAuth https://goshippo.com/docs/oauth/  with the SDK?

**Comment by jfriedr** [comment]
Once you have gotten the oauth bearer token for your customers via the link you shared you can use that within the client sdk code.  Once you have the user's Oauth token the client sdk detects the token type and makes the required changes to the Authorization header.  You can see this in the code of the repo here:

 https://github.com/goshippo/shippo-node-client/search?q=Bearer

Keep in mind that the above code simply changes the header so that API calls made with the Oauth token go with the "`Bearer`" token type rather than the `ShippoToken` which is used for regular API calls.
